/**
 * The catalog as a document: one table per family, each rule with its level, what insures it,
 * the phase, the standard's IDs and the reason. `abatty rules --md` prints it;
 * docs/CATALOG.md is that output, and a test keeps the two equal.
 */
import { stdIds } from "../core/gap-analysis.mjs";

/** @param {string} s */
const cell = (s) => stdIds(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

/**
 * @param {import("../rules/index.mjs").CatalogRule[]} rules
 * @param {{ title?: string }} [o]
 */
export function renderCatalogMarkdown(rules, o = {}) {
  const families = [...new Set(rules.map((r) => r.family))];
  const must = rules.filter((r) => r.level === "must").length;
  const by = (/** @type {string} */ e) => rules.filter((r) => r.enforcement === e).length;
  const md = [];
  md.push("---");
  md.push(`title: "${o.title || "Rule catalog"}"`);
  md.push(
    `description: "Every check abatty makes, as data: ${rules.length} rules in ${families.length} families, ${must} must and ${rules.length - must} should; once present, ${by("hard")} are insured by a machine that refuses, ${by("ratchet")} by a number that may only fall, ${by("review")} by the reviewer's checklist, ${by("prose")} by nothing yet. Generated by abatty rules --md; the test keeps this file equal to the catalog."`,
  );
  md.push("category: reference");
  md.push("status: living");
  md.push('audience: ["developer", "architect", "reviewer"]');
  md.push('tags: ["rules", "catalog", "standards", "generated"]');
  md.push('related: ["./README.md", "./ROADMAP.md"]');
  md.push("---");
  md.push("");
  md.push(`# ${o.title || "Rule catalog"}`);
  md.push("");
  md.push(
    `${rules.length} rules in ${families.length} families; ${must} must, ${rules.length - must} should. A rule is a check with a reason: \`abatty measure\` runs every one, \`abatty explain <ID>\` opens one against a repository. **Insured by** says what holds the rule once it is present: **hard**, a machine refuses the work (a lint error, a hook denial, a failing gate step); **ratchet**, a number that may only fall, with a per-file floor; **review**, an item of the reviewer's checklist; **prose**, written and checked by nothing yet. The standard's rule IDs are \`FAMILY.N\` (\`CODE.6\`), a namespace of their own that a repository's citation check never claims.`,
  );
  md.push("");
  md.push(
    `The rules come from profiles: the built-in \`synovitec\` profile is the standard the package was built on; a repository names the profiles it follows in its config (\`profiles\`), a file or a package exporting a profile of its own among them. A repository adds rules of its own in \`abatty.rules.mjs\` at its root (the same shape, \`export const rules = [...]\`) and waives one with a reason in its config (\`rules.waived\`); a waived rule is listed, not scored.`,
  );
  md.push("");
  for (const fam of families) {
    const list = rules.filter((r) => r.family === fam);
    md.push(`## ${fam}`);
    md.push("");
    md.push("| ID | Rule | Level | Insured by | Phase | Standard | Why |");
    md.push("|---|---|---|---|---|---|---|");
    for (const r of list)
      md.push(
        `| ${r.id} | ${cell(r.title)} | ${r.level} | ${r.enforcement} | ${r.phase} | ${cell((r.standard || []).join(", ")) || "-"} | ${cell(r.why)} |`,
      );
    md.push("");
  }
  return md.join("\n");
}
