/**
 * The evidence export: the mapping and its findings as a document somebody can put in front of a
 * reader, rather than a JSON file somebody has to be taught to read.
 *
 * It is written to be READ BY A SCEPTIC. The empty requirements come first, before the ones with
 * rules behind them, because a document of this kind is usually arranged the other way round and
 * that arrangement is how a reader ends up believing something nobody claimed. Every row says
 * what the named rules evidence and what they do not, in words, and the header says three times
 * over that a mapping is not a conformity assessment.
 */
import { REGULATION, mapRequirements, mappingShape } from "../profiles/cra-requirements.mjs";

/** @param {string} s */
const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

/**
 * @param {{ findings: import("../rules/index.mjs").Finding[], name: string, date: string, commit: string, version: string, score: number }} o
 * @returns {string}
 */
export function renderEvidence(o) {
  const rows = mapRequirements(o.findings);
  const shape = mappingShape();
  const empty = rows.filter((r) => !r.rules.length);
  const claimed = rows.filter((r) => r.rules.length);
  const md = [];
  md.push("---");
  md.push(`title: "Evidence against the essential requirements - ${o.name} - ${o.date}"`);
  md.push(
    `description: "Which engineering rules this repository holds that bear on each of the ${shape.total} essential requirements, and which requirements nothing here bears on at all (${shape.withoutRules} of them). A mapping, not a conformity assessment, and not legal advice. Generated by abatty evidence."`,
  );
  md.push("category: reference");
  md.push("status: stable");
  md.push('audience: ["architect", "reviewer"]');
  md.push('tags: ["evidence", "requirements", "generated"]');
  md.push(`last_verified: "${o.date}"`);
  md.push("---");
  md.push("");
  md.push(`# Evidence against the essential requirements`);
  md.push("");
  md.push(
    `**${o.name}**, commit \`${o.commit.slice(0, 12)}\`, read on ${o.date} by abatty ${o.version}.`,
  );
  md.push("");
  md.push("## Read this first");
  md.push("");
  md.push(`> ${REGULATION.warning}`);
  md.push("");
  md.push(
    `The source: ${REGULATION.name}. ${REGULATION.annex}. The requirement titles below are a short paraphrase for orientation and are **not** the regulation's wording; the references are there so you go and read it.`,
  );
  md.push("");
  md.push(
    `Of ${shape.total} requirements, **${shape.withoutRules} have no rule in this catalog that bears on them at all**, and ${shape.withRules} have at least one. That first number is the useful one, and it is why the empty requirements are listed before the others on this page.`,
  );
  md.push("");
  md.push("## The requirements nothing here bears on");
  md.push("");
  md.push(
    "No engineering rule in this catalog evidences any part of these. Nothing on this page should be read as progress towards them.",
  );
  md.push("");
  md.push("| Requirement | What it asks for | Why no rule bears on it |");
  md.push("|---|---|---|");
  for (const r of empty) md.push(`| ${r.id} | ${cell(r.title)} | ${cell(r.gap)} |`);
  md.push("");
  md.push("## The requirements some rule bears on");
  md.push("");
  md.push(
    "For each: what the named rules actually evidence, what they do not, and how each one reads in this repository today.",
  );
  md.push("");
  for (const r of claimed) {
    md.push(`### ${r.id} · ${r.title}`);
    md.push("");
    md.push(`**Standing here:** ${r.standing}.`);
    md.push("");
    md.push(`**What the rules below evidence:** ${r.covers}.`);
    md.push("");
    md.push(`**What they do not:** ${r.gap}.`);
    md.push("");
    md.push("| Rule | Status | Evidence |");
    md.push("|---|---|---|");
    for (const e of r.evidence) md.push(`| ${e.rule} | ${e.status} | ${cell(e.evidence) || "-"} |`);
    md.push("");
  }
  md.push("## How this was produced");
  md.push("");
  md.push(
    `Every status above is a rule of the catalog run against the tree at \`${o.commit.slice(0, 12)}\`; nothing was entered by hand and nothing can be. The repository's overall reading was ${o.score}/100, which is a trend for comparing readings of the same repository and is not a grade, not a percentage of conformity, and not a number to put in front of anybody as one.`,
  );
  md.push("");
  md.push(
    "`abatty attest` produces the same facts as a signed in-toto predicate for a machine; this page is the same facts for a person. Neither is a conformity assessment.",
  );
  md.push("");
  return md.join("\n");
}
