/**
 * The night report as Markdown, in the shape of the other night documents: front matter, the
 * sessions, the Stop gate, the guard, the phases and decisions, the proposed lessons.
 */

import { describeFootprint } from "./footprint.mjs";

/** @typedef {import("./report.mjs").NightReport} NightReport */

/** The report as Markdown, in the shape of the other night documents. @param {NightReport} r */
export function renderNightReport(r) {
  const spent = r.sessions.reduce((s, x) => s + x.cost, 0);
  const done = r.phases.filter((p) => p && p.status === "done").length;
  const blocked = r.phases.filter((p) => p && p.status === "blocked").length;
  const lines = [
    "---",
    `title: "Night report ${r.date}"`,
    `description: "The distillation of the night of ${r.date} on ${r.branch}: ${r.sessions.length} session(s), ${spent.toFixed(2)} USD, ${done} phase(s) done, ${blocked} blocked, ${r.receipts.length} Stop receipt(s), ${r.denials.length} denial(s), ${r.lessons.length} lesson(s) proposed. Generated by abatty night-report; the proposals are a human's to accept into the lessons catalogue."`,
    "category: governance",
    "status: living",
    'audience: ["developer", "architect"]',
    'tags: ["night", "report", "lessons"]',
    "---",
    "",
    `# Night report ${r.date}`,
    "",
    `Branch \`${r.branch}\` from \`${r.base}\` · ${r.sessions.length} session(s) · ${spent.toFixed(2)} USD · ${r.commits.length} commit(s) · ${done} phase(s) done, ${blocked} blocked · sandbox ${r.run?.sandbox || "none"}${r.run?.spent ? ` · ${r.run.spent.sessions} session(s) and ${r.run.spent.tokens} tokens against the allowance` : ""}${r.run?.status && r.run.status !== "done" ? ` · run ${r.run.status}` : ""}.`,
    "",
    "## Sessions",
    "",
    `**What the harness cost to carry.** ${describeFootprint(r.footprint, r.footprintShare)}.`,
    "",
    "| Part | kB | ~tokens |",
    "|---|---|---|",
    ...r.footprint.parts.map((p) => `| ${p.part} | ${(p.bytes / 1024).toFixed(1)} | ${p.tokens} |`),
    "",
    "| Session | Phase | Cost | Denials | Outcome |",
    "|---|---|---|---|---|",
    ...r.sessions.map(
      (s) =>
        `| ${s.name} | ${s.phase} | ${s.cost.toFixed(2)} | ${s.denials} | ${s.crashed ? "no result" : s.isError ? "error" : "ok"} |`,
    ),
    "",
    "## Stop gate",
    "",
    ...(r.receipts.length
      ? r.receipts.map(
          (x) =>
            `- ${x.sessionId || "?"}${x.phase !== null ? ` (phase ${x.phase})` : ""}: ${x.decision}${x.blocks ? `, ${x.blocks} block(s)` : ""}${x.failedCheck ? `, last on ${x.failedCheck}` : ""}${x.reason ? ` - ${x.reason}` : ""}`,
        )
      : ["- no receipt"]),
    ...(r.blocks.length
      ? [
          "",
          `${r.blocks.length} block(s) in all:`,
          ...r.blocks.map(
            (b) =>
              `- ${b.at.slice(11, 19)} ${b.sessionId || "?"} block ${b.block} on ${b.check}: ${b.reason}`,
          ),
        ]
      : []),
    "",
    "## Guard",
    "",
    ...(r.denials.length
      ? r.denials.map((x) => `- ${x.at.slice(11, 19)} ${x.tool}: \`${x.what.slice(0, 120)}\``)
      : ["- no denial"]),
    "",
    "## Phases and decisions",
    "",
    ...(r.phases.length
      ? r.phases.map((p) => `- phase ${p.id}: ${p.status}${p.reason ? ` - ${p.reason}` : ""}`)
      : ["- no state file"]),
    ...(Object.keys(r.decisions).length
      ? ["", ...Object.entries(r.decisions).map(([k, n]) => `- decision: ${k} × ${n}`)]
      : []),
    "",
    "## Proposed lessons",
    "",
    ...(r.lessons.length
      ? r.lessons.flatMap((l) => [
          `### ${l.title}`,
          "",
          `- **Lesson:** ${l.lesson} (${r.branch}, ${r.date})`,
          `- **Caught by:** ${l.check}`,
          `- **Evidence:** ${l.evidence.join(" · ")}`,
          "",
        ])
      : [
          "Nothing recurred and nothing failed: no lesson proposed. A quiet night is evidence too.",
          "",
        ]),
    "A proposal becomes a lesson when a human writes it into the lessons catalogue in its one-sentence shape, with the check that now catches it.",
    "",
  ];
  return lines.join("\n");
}
