/** Whether a file is one `abatty ci` wrote, and so one it may write again. @param {string} text */
export function isGenerated(text: string): boolean;
/**
 * Whether a pipeline runs the gate, and how, read from its commands (never its comments): the
 * gate directly, or a package script whose body is the gate. `gate --fast` is named apart,
 * because it leaves out the suites a pipeline exists to run where Docker is.
 * @param {string} text the pipeline @param {Record<string, string>} scripts the package's scripts
 * @returns {{ runs: boolean, how: string }}
 */
export function runsGate(text: string, scripts: Record<string, string>): {
    runs: boolean;
    how: string;
};
/**
 * A pipeline this package did not write. `abatty ci` generates one per step, but a repository may
 * run the gate itself from a pipeline it keeps by hand (its own env, pins, services and
 * concurrency), which is the gate's rule in its strongest form: one implementation, every caller.
 * Overwriting such a file dropped what the repository had added and put older pins back; judging
 * it by equality with the generated text called it behind forever. It is judged instead by what
 * it runs.
 */
/** The first line of every pipeline `abatty ci` writes: the mark that it may be regenerated. */
export const GENERATED_MARK: "# Generated by `abatty ci`";
