/**
 * CI from the gate: the pipeline of a repository is generated from its preset's gate
 * definition - the same steps, in the same order, plus the secret scan, the audit and the
 * publish step to the hosted dashboard - so the gate and CI cannot list different steps. Two
 * providers today, Woodpecker and GitHub Actions; a pull-request template; and a ruleset for
 * the organisation that refuses branch names naming a tool and requires the checks.
 *
 * The ruleset is PRINTED, never written into a repository: it carries the vocabulary in the
 * open, which a repository that scrubs must not.
 */
import { TERMS } from "../core/vocabulary.mjs";

/**
 * @typedef {import("../presets/index.mjs").Preset} Preset
 * @typedef {{ base?: string, node?: string, publish?: boolean }} CiOptions
 * @typedef {{ name: string, command: string, when?: "always" | "db" | "browser" }} CiStep
 */

export const PROVIDERS = ["woodpecker", "github"];

/** The steps of a preset's CI, in the gate's order, provider-neutral. @param {Preset} preset @param {CiOptions} [o] */
export function ciSteps(preset, o = {}) {
  const base = o.base || "main";
  /** @type {CiStep[]} */
  const steps = [];
  for (const s of preset.gate.always) {
    if (s.command) steps.push({ name: s.label, command: s.command.join(" "), when: "always" });
    else if (s.script === "standards")
      steps.push({
        name: s.label,
        command: `git fetch --no-tags origin ${base} && npm run -s standards -- --range origin/${base}..HEAD`,
        when: "always",
      });
    else if (s.script)
      steps.push({ name: s.label, command: `npm run -s ${s.script}`, when: "always" });
  }
  steps.push({
    name: "secret scan (SEC.1)",
    command: `git fetch --no-tags origin ${base} && npx abatty secrets --range origin/${base}..HEAD`,
    when: "always",
  });
  steps.push({ name: "audit (SEC.1)", command: "npm audit --audit-level=high", when: "always" });
  // The same step the gate runs, so the two cannot list different ones. It is a no-op where the
  // repository did not opt in, exactly as the commit-msg hook is, and the command names no tool.
  steps.push({
    name: "no trace of the tools (scrub)",
    command: "npx abatty scrub .",
    when: "always",
  });
  for (const suite of preset.gate.suites) {
    const db = /database|DATA.4/i.test(suite.name);
    for (const s of suite.steps)
      if (s.script || s.command)
        steps.push({
          name: `${s.label} · ${suite.name}`,
          command: s.command ? s.command.join(" ") : `npm run -s ${s.script}`,
          when: db ? "db" : "browser",
        });
  }
  if (o.publish !== false)
    steps.push({
      name: "publish the report to the dashboard",
      command: 'npx abatty publish --to "$ABATTY_DASHBOARD" --token "$ABATTY_TOKEN"',
      when: "always",
    });
  return steps;
}

/** A YAML scalar, quoted when it must be. @param {string} s */
function y(s) {
  return /^[\w./ :=+()-]+$/.test(s) && !/^[\s-]|:\s|\s$/.test(s) ? s : JSON.stringify(s);
}
/** A step's name as an identifier. @param {string} name */
function ident(name) {
  return (
    name
      .toLowerCase()
      .replace(/\(.*?\)/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "step"
  );
}

/**
 * The Woodpecker pipeline: one `checks` pipeline with the always-on steps, the suites in their
 * own pipelines depending on it, Postgres as a service where the preset has a database suite.
 * @param {Preset} preset @param {CiOptions} [o]
 */
export function renderWoodpecker(preset, o = {}) {
  const node = o.node || "22";
  const steps = ciSteps(preset, o);
  const image = `node:${node}`;
  /** @param {CiStep} s */
  const step = (s) => {
    const lines = [`  ${ident(s.name)}:`];
    if (/abatty publish/.test(s.command))
      lines.push(
        `    image: ${image}`,
        `    secrets: [abatty_dashboard, abatty_token]`,
        `    when:`,
        `      evaluate: 'ABATTY_DASHBOARD != ""'`,
        `    commands:`,
        `      - ${y(s.command)}`,
      );
    else lines.push(`    image: ${image}`, `    commands:`, `      - ${y(s.command)}`);
    return lines.join("\n");
  };
  const always = steps.filter((s) => s.when === "always");
  const db = steps.filter((s) => s.when === "db");
  const browser = steps.filter((s) => s.when === "browser");
  const out = [
    `# Generated by \`abatty ci\` from the ${preset.id} preset's gate: the same steps, in the same order.`,
    `# Regenerate after a gate change; \`abatty ci --check\` says when this file is behind.`,
    `when:`,
    `  - event: [push, pull_request]`,
    ``,
    `steps:`,
    `  install:`,
    `    image: ${image}`,
    `    commands:`,
    `      - npm ci`,
    ...always.map(step),
    ``,
  ];
  if (db.length) {
    out.push(
      `---`,
      `# The database suite, on a real Postgres.`,
      `depends_on: [checks]`,
      `when:`,
      `  - event: [push, pull_request]`,
      ``,
      `services:`,
      `  postgres:`,
      `    image: postgres:16`,
      `    environment:`,
      `      POSTGRES_PASSWORD: postgres`,
      `      POSTGRES_DB: test`,
      ``,
      `steps:`,
      `  install:`,
      `    image: ${image}`,
      `    commands:`,
      `      - npm ci`,
    );
    for (const s of db)
      out.push(
        `  ${ident(s.name)}:`,
        `    image: ${image}`,
        `    environment:`,
        `      DATABASE_URL: postgres://postgres:postgres@postgres:5432/test`,
        `    commands:`,
        `      - ${y(s.command)}`,
      );
    out.push(``);
  }
  if (browser.length) {
    out.push(
      `---`,
      `# The browser suite with axe, over the built output.`,
      `depends_on: [checks]`,
      `when:`,
      `  - event: [push, pull_request]`,
      ``,
      `steps:`,
      `  install:`,
      `    image: mcr.microsoft.com/playwright:v1.48.0-noble`,
      `    commands:`,
      `      - npm ci`,
    );
    for (const s of browser)
      out.push(
        `  ${ident(s.name)}:`,
        `    image: mcr.microsoft.com/playwright:v1.48.0-noble`,
        `    commands:`,
        `      - ${y(s.command)}`,
      );
    out.push(``);
  }
  return out.join("\n");
}

/**
 * The GitHub Actions workflow: a `checks` job with the always-on steps, a `database` job with a
 * Postgres service, a `browser` job, the publish step guarded by the secret.
 * @param {Preset} preset @param {CiOptions} [o]
 */
export function renderGithubActions(preset, o = {}) {
  const node = o.node || "22";
  const steps = ciSteps(preset, o);
  /** @param {CiStep} s */
  const step = (s) => {
    if (/abatty publish/.test(s.command))
      return [
        `      - name: ${y(s.name)}`,
        `        if: \${{ env.ABATTY_DASHBOARD != '' }}`,
        `        env:`,
        `          ABATTY_DASHBOARD: \${{ secrets.ABATTY_DASHBOARD }}`,
        `          ABATTY_TOKEN: \${{ secrets.ABATTY_TOKEN }}`,
        `        run: ${y(s.command)}`,
      ].join("\n");
    return [`      - name: ${y(s.name)}`, `        run: ${y(s.command)}`].join("\n");
  };
  const setup = [
    `      - uses: actions/checkout@v4`,
    `        with:`,
    `          fetch-depth: 0`,
    `      - uses: actions/setup-node@v4`,
    `        with:`,
    `          node-version: "${node}"`,
    `          cache: npm`,
    `      - run: npm ci`,
  ];
  const always = steps.filter((s) => s.when === "always");
  const db = steps.filter((s) => s.when === "db");
  const browser = steps.filter((s) => s.when === "browser");
  const out = [
    `# Generated by \`abatty ci\` from the ${preset.id} preset's gate: the same steps, in the same order.`,
    `# Regenerate after a gate change; \`abatty ci --check\` says when this file is behind.`,
    `name: checks`,
    `on:`,
    `  push:`,
    `  pull_request:`,
    `permissions:`,
    `  contents: read`,
    // The findings are uploaded to code scanning, which is what puts them on the diff of the
    // change under review rather than in a report nobody opens.
    `  security-events: write`,
    `jobs:`,
    `  checks:`,
    `    runs-on: ubuntu-latest`,
    `    steps:`,
    ...setup,
    ...always.map(step),
    // Emitted and uploaded even when a step above went red: a run that failed is exactly the run
    // whose findings a reviewer needs on the diff.
    // A bypass nobody can see afterwards is a gate with a hole nobody can measure.
    `      - name: the bypass rate of this push`,
    `        if: always()`,
    `        run: npx abatty report --json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const b=JSON.parse(s).bypass||{};console.log(\`bypass: \${b.bypassed||0} of \${b.commits||0} commit(s) got past the hook without saying why (\${b.rate||0}%), \${b.reasoned||0} with a reason\`);process.exit(b.bypassed?1:0)})"`,
    `      - name: findings as SARIF`,
    `        if: always()`,
    `        run: npx abatty ratchet --range auto --sarif > abatty.sarif || true`,
    `      - name: upload the findings`,
    `        if: always()`,
    `        uses: github/codeql-action/upload-sarif@v3`,
    `        with:`,
    `          sarif_file: abatty.sarif`,
    `          category: abatty`,
  ];
  if (db.length) {
    out.push(
      `  database:`,
      `    needs: checks`,
      `    runs-on: ubuntu-latest`,
      `    services:`,
      `      postgres:`,
      `        image: postgres:16`,
      `        env:`,
      `          POSTGRES_PASSWORD: postgres`,
      `          POSTGRES_DB: test`,
      `        ports: ["5432:5432"]`,
      `        options: >-`,
      `          --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 10`,
      `    env:`,
      `      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test`,
      `    steps:`,
      ...setup,
      ...db.map(step),
    );
  }
  if (browser.length) {
    out.push(
      `  browser:`,
      `    needs: checks`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      ...setup,
      `      - run: npx playwright install --with-deps`,
      ...browser.map(step),
    );
  }
  return out.join("\n") + "\n";
}
