/**
 * The GitHub Actions renderer of the generated pipeline: a `checks` job with the always-on
 * steps, a `database` job with a Postgres service, a `browser` job, the publish step guarded
 * by the secret, and the findings, the bypass rate and the signed conformance statement
 * uploaded from the same run.
 */
import { ciSteps, tooling, y } from "./generate.mjs";

/**
 * Every action the generated pipeline uses, pinned to the commit its version tag named when this
 * list was written: a tag can be moved to other code after the fact, and the pipeline that runs
 * the gate is the last place to take that on trust. The version stays beside it for the reader.
 */
export const ACTIONS = {
  checkout: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0",
  setupNode: "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0",
  setupPnpm: "pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0",
  setupBun: "oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0",
  uploadSarif:
    "github/codeql-action/upload-sarif@1190a975f95ce23525efb6a3fc21ea29567c1b52 # v3.38.2",
  attest: "actions/attest@ce27ba3b4a9a139d9a20a4a07d69fabb52f1e5bc # v2.4.0",
};

/**
 * @typedef {import("./generate.mjs").CiStep} CiStep
 * @typedef {import("./generate.mjs").CiOptions} CiOptions
 * @typedef {import("../presets/index.mjs").Preset} Preset
 */

/**
 * The GitHub Actions workflow: a `checks` job with the always-on steps, a `database` job with a
 * Postgres service, a `browser` job, the publish step guarded by the secret.
 * @param {Preset} preset @param {CiOptions} [o]
 */
export function renderGithubActions(preset, o = {}) {
  const node = o.node || "22";
  const steps = ciSteps(preset, o);
  const t = tooling(o);
  /** @param {CiStep} s */
  const step = (s) => {
    if (s.absent) return `      # ${s.name}: ${s.absent}`;
    if (/abatty publish/.test(s.command))
      return [
        `      - name: ${y(s.name)}`,
        `        if: \${{ env.ABATTY_DASHBOARD != '' }}`,
        `        env:`,
        `          ABATTY_DASHBOARD: \${{ secrets.ABATTY_DASHBOARD }}`,
        `          ABATTY_TOKEN: \${{ secrets.ABATTY_TOKEN }}`,
        `        run: ${y(s.command)}`,
      ].join("\n");
    return [`      - name: ${y(s.name)}`, `        run: ${y(s.command)}`].join("\n");
  };
  // The runner's toolchain follows the lockfile: pnpm is installed before node so the cache
  // can find it, bun brings its own action, and the install is the manager's frozen one.
  const setup = [
    `      - uses: ${ACTIONS.checkout}`,
    `        with:`,
    `          fetch-depth: 0`,
    ...(t.id === "pnpm" ? [`      - uses: ${ACTIONS.setupPnpm}`] : []),
    ...(t.id === "bun" ? [`      - uses: ${ACTIONS.setupBun}`] : []),
    `      - uses: ${ACTIONS.setupNode}`,
    `        with:`,
    `          node-version: "${node}"`,
    ...(t.id === "bun" ? [] : [`          cache: ${t.id}`]),
    `      - run: ${t.install}`,
  ];
  const always = steps.filter((s) => s.when === "always");
  const db = steps.filter((s) => s.when === "db");
  const browser = steps.filter((s) => s.when === "browser");
  const out = [
    `# Generated by \`abatty ci\` from the ${preset.id} preset's gate: the same steps, in the same order.`,
    `# Regenerate after a gate change; \`abatty ci --check\` says when this file is behind.`,
    `name: checks`,
    `on:`,
    `  push:`,
    `  pull_request:`,
    // A review re-runs the floors job alone: the approval arrives after the checks ran.
    `  pull_request_review:`,
    `    types: [submitted, dismissed]`,
    `permissions:`,
    `  contents: read`,
    `  pull-requests: read`,
    // The workload identity the signature is made with, and the write the transparency log needs.
    `  id-token: write`,
    `  attestations: write`,
    // The findings are uploaded to code scanning, which is what puts them on the diff of the
    // change under review rather than in a report nobody opens.
    `  security-events: write`,
    `jobs:`,
    `  checks:`,
    `    if: github.event_name != 'pull_request_review'`,
    `    runs-on: ubuntu-latest`,
    `    steps:`,
    ...setup,
    ...always.map(step),
    // Emitted and uploaded even when a step above went red: a run that failed is exactly the run
    // whose findings a reviewer needs on the diff.
    // A bypass nobody can see afterwards is a gate with a hole nobody can measure.
    `      - name: the bypass rate of this push`,
    `        if: always()`,
    `        run: ${t.exec("abatty")} report --json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const b=JSON.parse(s).bypass||{};console.log(\`bypass: \${b.bypassed||0} of \${b.commits||0} commit(s) got past the hook without saying why (\${b.rate||0}%), \${b.reasoned||0} with a reason\`);process.exit(b.bypassed?1:0)})"`,
    `      - name: findings as SARIF`,
    `        if: always()`,
    // Exit 3 is "written, with findings"; anything else but 0 is a crash, which a `|| true` read
    // as a pass, uploading nothing while the step showed green.
    `        run: |`,
    `          ${t.exec("abatty")} ratchet --range auto --sarif > abatty.sarif || code=$?`,
    `          [ "\${code:-0}" -eq 0 ] || [ "\${code:-0}" -eq 3 ]`,
    `          test -s abatty.sarif`,
    `      - name: upload the findings`,
    `        if: always()`,
    `        uses: ${ACTIONS.uploadSarif}`,
    `        with:`,
    `          sarif_file: abatty.sarif`,
    `          category: abatty`,
    // The conformance statement, signed by the RUN rather than by a key anybody holds.
    //
    // WHY here and not in the package: a signature is worth the identity behind it, and the only
    // identity available to a measurement tool would be a key on a developer's machine or a
    // secret in a repository, which is the weakest attestation of the two and the one most
    // likely to leak. The pipeline already has a short-lived workload identity that no human can
    // export, and the platform's own attestation action turns it into a signature in the
    // established transparency log. So this package prints the statement and the pipeline signs
    // it, with the run's identity, for free, in the store every verifier already reads.
    `      - name: the conformance statement`,
    `        if: always()`,
    // 3 means written, with the statement saying the gate's controls never ran here.
    `        run: |`,
    `          ${t.exec("abatty")} attest --out abatty-conformance.json || code=$?`,
    `          [ "\${code:-0}" -eq 0 ] || [ "\${code:-0}" -eq 3 ]`,
    `          test -s abatty-conformance.json`,
    `      - name: sign it with this run's identity`,
    `        if: always()`,
    `        uses: ${ACTIONS.attest}`,
    `        with:`,
    `          subject-path: abatty-conformance.json`,
    `          predicate-type: https://abatty.dev/attestation/conformance/v1`,
    `          predicate-path: abatty-conformance.json`,
  ];
  // A floor raised or dropped lands only with an approval its raiser cannot give itself: a
  // review of the head commit by somebody other than the author (src/core/raises.mjs).
  out.push(
    `  floors:`,
    `    if: github.event_name != 'push'`,
    `    runs-on: ubuntu-latest`,
    `    steps:`,
    ...setup,
    `      - name: a loosened floor needs a second person's approval`,
    `        env:`,
    `          GH_TOKEN: \${{ github.token }}`,
    `        run: ${t.exec("abatty")} raises --base origin/\${{ github.event.pull_request.base.ref }} --require-review \${{ github.event.pull_request.number }}`,
  );
  /** A job whose every step is absent is written as the comments, not as a job with no steps. @param {string} job @param {CiStep[]} list */
  const onlyAbsent = (job, list) =>
    out.push(
      `  # ${job}: no runnable step yet`,
      ...list.map((s) => `  #   ${s.name}: ${s.absent}`),
    );
  if (db.length && db.every((s) => s.absent)) onlyAbsent("database", db);
  else if (db.length) {
    out.push(
      `  database:`,
      `    needs: checks`,
      `    runs-on: ubuntu-latest`,
      `    services:`,
      `      postgres:`,
      `        image: postgres:16`,
      `        env:`,
      `          POSTGRES_PASSWORD: postgres`,
      `          POSTGRES_DB: test`,
      `        ports: ["5432:5432"]`,
      `        options: >-`,
      `          --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 10`,
      `    env:`,
      `      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test`,
      `    steps:`,
      ...setup,
      ...db.map(step),
    );
  }
  if (browser.length && browser.every((s) => s.absent)) onlyAbsent("browser", browser);
  else if (browser.length) {
    out.push(
      `  browser:`,
      `    needs: checks`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      ...setup,
      `      - run: ${t.exec("playwright")} install --with-deps`,
      ...browser.map(step),
    );
  }
  return out.join("\n") + "\n";
}
