/**
 * The GitHub Actions renderer of the generated pipeline: a `checks` job with the always-on
 * steps, a `database` job with a Postgres service, a `browser` job, the publish step guarded
 * by the secret, and the findings, the bypass rate and the signed conformance statement
 * uploaded from the same run.
 */
import { ciSteps, tooling, y } from "./generate.mjs";

/**
 * @typedef {import("./generate.mjs").CiStep} CiStep
 * @typedef {import("./generate.mjs").CiOptions} CiOptions
 * @typedef {import("../presets/index.mjs").Preset} Preset
 */

/**
 * The GitHub Actions workflow: a `checks` job with the always-on steps, a `database` job with a
 * Postgres service, a `browser` job, the publish step guarded by the secret.
 * @param {Preset} preset @param {CiOptions} [o]
 */
export function renderGithubActions(preset, o = {}) {
  const node = o.node || "22";
  const steps = ciSteps(preset, o);
  const t = tooling(o);
  /** @param {CiStep} s */
  const step = (s) => {
    if (s.absent) return `      # ${s.name}: ${s.absent}`;
    if (/abatty publish/.test(s.command))
      return [
        `      - name: ${y(s.name)}`,
        `        if: \${{ env.ABATTY_DASHBOARD != '' }}`,
        `        env:`,
        `          ABATTY_DASHBOARD: \${{ secrets.ABATTY_DASHBOARD }}`,
        `          ABATTY_TOKEN: \${{ secrets.ABATTY_TOKEN }}`,
        `        run: ${y(s.command)}`,
      ].join("\n");
    return [`      - name: ${y(s.name)}`, `        run: ${y(s.command)}`].join("\n");
  };
  // The runner's toolchain follows the lockfile: pnpm is installed before node so the cache
  // can find it, bun brings its own action, and the install is the manager's frozen one.
  const setup = [
    `      - uses: actions/checkout@v4`,
    `        with:`,
    `          fetch-depth: 0`,
    ...(t.id === "pnpm" ? [`      - uses: pnpm/action-setup@v4`] : []),
    ...(t.id === "bun" ? [`      - uses: oven-sh/setup-bun@v2`] : []),
    `      - uses: actions/setup-node@v4`,
    `        with:`,
    `          node-version: "${node}"`,
    ...(t.id === "bun" ? [] : [`          cache: ${t.id}`]),
    `      - run: ${t.install}`,
  ];
  const always = steps.filter((s) => s.when === "always");
  const db = steps.filter((s) => s.when === "db");
  const browser = steps.filter((s) => s.when === "browser");
  const out = [
    `# Generated by \`abatty ci\` from the ${preset.id} preset's gate: the same steps, in the same order.`,
    `# Regenerate after a gate change; \`abatty ci --check\` says when this file is behind.`,
    `name: checks`,
    `on:`,
    `  push:`,
    `  pull_request:`,
    `permissions:`,
    `  contents: read`,
    // The workload identity the signature is made with, and the write the transparency log needs.
    `  id-token: write`,
    `  attestations: write`,
    // The findings are uploaded to code scanning, which is what puts them on the diff of the
    // change under review rather than in a report nobody opens.
    `  security-events: write`,
    `jobs:`,
    `  checks:`,
    `    runs-on: ubuntu-latest`,
    `    steps:`,
    ...setup,
    ...always.map(step),
    // Emitted and uploaded even when a step above went red: a run that failed is exactly the run
    // whose findings a reviewer needs on the diff.
    // A bypass nobody can see afterwards is a gate with a hole nobody can measure.
    `      - name: the bypass rate of this push`,
    `        if: always()`,
    `        run: ${t.exec("abatty")} report --json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const b=JSON.parse(s).bypass||{};console.log(\`bypass: \${b.bypassed||0} of \${b.commits||0} commit(s) got past the hook without saying why (\${b.rate||0}%), \${b.reasoned||0} with a reason\`);process.exit(b.bypassed?1:0)})"`,
    `      - name: findings as SARIF`,
    `        if: always()`,
    `        run: ${t.exec("abatty")} ratchet --range auto --sarif > abatty.sarif || true`,
    `      - name: upload the findings`,
    `        if: always()`,
    `        uses: github/codeql-action/upload-sarif@v3`,
    `        with:`,
    `          sarif_file: abatty.sarif`,
    `          category: abatty`,
    // The conformance statement, signed by the RUN rather than by a key anybody holds.
    //
    // WHY here and not in the package: a signature is worth the identity behind it, and the only
    // identity available to a measurement tool would be a key on a developer's machine or a
    // secret in a repository, which is the weakest attestation of the two and the one most
    // likely to leak. The pipeline already has a short-lived workload identity that no human can
    // export, and the platform's own attestation action turns it into a signature in the
    // established transparency log. So this package prints the statement and the pipeline signs
    // it, with the run's identity, for free, in the store every verifier already reads.
    `      - name: the conformance statement`,
    `        if: always()`,
    `        run: ${t.exec("abatty")} attest --out abatty-conformance.json || true`,
    `      - name: sign it with this run's identity`,
    `        if: always()`,
    `        uses: actions/attest@v2`,
    `        with:`,
    `          subject-path: abatty-conformance.json`,
    `          predicate-type: https://abatty.dev/attestation/conformance/v1`,
    `          predicate-path: abatty-conformance.json`,
  ];
  /** A job whose every step is absent is written as the comments, not as a job with no steps. @param {string} job @param {CiStep[]} list */
  const onlyAbsent = (job, list) =>
    out.push(
      `  # ${job}: no runnable step yet`,
      ...list.map((s) => `  #   ${s.name}: ${s.absent}`),
    );
  if (db.length && db.every((s) => s.absent)) onlyAbsent("database", db);
  else if (db.length) {
    out.push(
      `  database:`,
      `    needs: checks`,
      `    runs-on: ubuntu-latest`,
      `    services:`,
      `      postgres:`,
      `        image: postgres:16`,
      `        env:`,
      `          POSTGRES_PASSWORD: postgres`,
      `          POSTGRES_DB: test`,
      `        ports: ["5432:5432"]`,
      `        options: >-`,
      `          --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 10`,
      `    env:`,
      `      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test`,
      `    steps:`,
      ...setup,
      ...db.map(step),
    );
  }
  if (browser.length && browser.every((s) => s.absent)) onlyAbsent("browser", browser);
  else if (browser.length) {
    out.push(
      `  browser:`,
      `    needs: checks`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      ...setup,
      `      - run: ${t.exec("playwright")} install --with-deps`,
      ...browser.map(step),
    );
  }
  return out.join("\n") + "\n";
}
