/**
 * A pipeline this package did not write. `abatty ci` generates one per step, but a repository may
 * run the gate itself from a pipeline it keeps by hand (its own env, pins, services and
 * concurrency), which is the gate's rule in its strongest form: one implementation, every caller.
 * Overwriting such a file dropped what the repository had added and put older pins back; judging
 * it by equality with the generated text called it behind forever. It is judged instead by what
 * it runs.
 */

/** The first line of every pipeline `abatty ci` writes: the mark that it may be regenerated. */
export const GENERATED_MARK = "# Generated by `abatty ci`";

/** Whether a file is one `abatty ci` wrote, and so one it may write again. @param {string} text */
export function isGenerated(text) {
  return text.trimStart().startsWith(GENERATED_MARK);
}

/** A script body that runs the whole gate: the command itself, or the older script form. */
const WHOLE_GATE = /\babatty(?:\.mjs)?\s+gate\b(?![^&|;]*--fast)|scripts\/ci\/gate\.m?js/;
/** A script body that runs the gate without its suites. */
const FAST_GATE = /\babatty(?:\.mjs)?\s+gate\b[^&|;]*--fast/;

/**
 * Whether a pipeline runs the gate, and how, read from its commands (never its comments): the
 * gate directly, or a package script whose body is the gate. `gate --fast` is named apart,
 * because it leaves out the suites a pipeline exists to run where Docker is.
 * @param {string} text the pipeline @param {Record<string, string>} scripts the package's scripts
 * @returns {{ runs: boolean, how: string }}
 */
export function runsGate(text, scripts) {
  // Commands only: a comment, and a `name:` (a job's, a step's, the workflow's), say what a
  // pipeline is called, never what it runs; `name: abatty gate` read as running it.
  const commands = text.replace(/^\s*#.*$/gm, "").replace(/^\s*-?\s*name\s*:.*$/gm, "");
  const direct = commands.match(/\babatty\s+gate\b[^\n]*/);
  if (direct && !/--fast/.test(direct[0])) return { runs: true, how: "runs `abatty gate`" };
  /** @type {string | null} */
  let fast = direct ? "abatty gate --fast" : null;
  for (const [name, body] of Object.entries(scripts)) {
    const called = new RegExp(
      `\\b(?:npm|pnpm|yarn|bun)\\s+(?:run\\s+)?(?:-s\\s+|--silent\\s+)?${escape(name)}(?![\\w:-])`,
    ).test(commands);
    if (!called) continue;
    if (WHOLE_GATE.test(body)) return { runs: true, how: `runs the \`${name}\` script (the gate)` };
    if (FAST_GATE.test(body)) fast = `the \`${name}\` script`;
  }
  return {
    runs: false,
    how: fast
      ? `runs ${fast}, which leaves out the suites; CI is where they run`
      : "runs neither the gate nor a script that does",
  };
}

/** @param {string} s */
function escape(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
