/**
 * The Woodpecker renderer of the generated pipeline: one `checks` pipeline with the always-on
 * steps, the suites as their own pipelines depending on it, Postgres as a service where the
 * preset has a database suite.
 */
import { ciSteps, ident, tooling, y } from "./generate.mjs";

/**
 * @typedef {import("./generate.mjs").CiStep} CiStep
 * @typedef {import("./generate.mjs").CiOptions} CiOptions
 * @typedef {import("../presets/index.mjs").Preset} Preset
 */

/**
 * The Woodpecker pipeline: one `checks` pipeline with the always-on steps, the suites in their
 * own pipelines depending on it, Postgres as a service where the preset has a database suite.
 * @param {Preset} preset @param {CiOptions} [o]
 */
export function renderWoodpecker(preset, o = {}) {
  const node = o.node || "22";
  const steps = ciSteps(preset, o);
  const t = tooling(o);
  // A node image carries corepack, which puts pnpm and yarn on PATH from the `packageManager`
  // field; bun ships its own image.
  const image = t.id === "bun" ? "oven/bun:1" : `node:${node}`;
  const install =
    t.id === "pnpm" || t.id === "yarn"
      ? [`      - corepack enable`, `      - ${t.install}`]
      : [`      - ${t.install}`];
  /** @param {CiStep} s */
  const step = (s) => {
    if (s.absent) return `  # ${ident(s.name)}: ${s.absent}`;
    const lines = [`  ${ident(s.name)}:`];
    if (/abatty publish/.test(s.command))
      lines.push(
        `    image: ${image}`,
        `    secrets: [abatty_dashboard, abatty_token]`,
        `    when:`,
        `      evaluate: 'ABATTY_DASHBOARD != ""'`,
        `    commands:`,
        `      - ${y(s.command)}`,
      );
    else lines.push(`    image: ${image}`, `    commands:`, `      - ${y(s.command)}`);
    return lines.join("\n");
  };
  const always = steps.filter((s) => s.when === "always");
  const db = steps.filter((s) => s.when === "db");
  const browser = steps.filter((s) => s.when === "browser");
  const out = [
    `# Generated by \`abatty ci\` from the ${preset.id} preset's gate: the same steps, in the same order.`,
    `# Regenerate after a gate change; \`abatty ci --check\` says when this file is behind.`,
    `when:`,
    `  - event: [push, pull_request]`,
    ``,
    `steps:`,
    `  install:`,
    `    image: ${image}`,
    `    commands:`,
    ...install,
    ...always.map(step),
    ``,
  ];
  /** @param {string} job @param {CiStep[]} list */
  const onlyAbsent = (job, list) =>
    out.push(
      `# ${job}: no runnable step yet`,
      ...list.map((s) => `#   ${s.name}: ${s.absent}`),
      ``,
    );
  if (db.length && db.every((s) => s.absent)) onlyAbsent("the database suite", db);
  else if (db.length) {
    out.push(
      `---`,
      `# The database suite, on a real Postgres.`,
      `depends_on: [checks]`,
      `when:`,
      `  - event: [push, pull_request]`,
      ``,
      `services:`,
      `  postgres:`,
      `    image: postgres:16`,
      `    environment:`,
      `      POSTGRES_PASSWORD: postgres`,
      `      POSTGRES_DB: test`,
      ``,
      `steps:`,
      `  install:`,
      `    image: ${image}`,
      `    commands:`,
      ...install,
    );
    for (const s of db)
      if (s.absent) out.push(`  # ${ident(s.name)}: ${s.absent}`);
      else
        out.push(
          `  ${ident(s.name)}:`,
          `    image: ${image}`,
          `    environment:`,
          `      DATABASE_URL: postgres://postgres:postgres@postgres:5432/test`,
          `    commands:`,
          `      - ${y(s.command)}`,
        );
    out.push(``);
  }
  if (browser.length && browser.every((s) => s.absent)) onlyAbsent("the browser suite", browser);
  else if (browser.length) {
    out.push(
      `---`,
      `# The browser suite with axe, over the built output.`,
      `depends_on: [checks]`,
      `when:`,
      `  - event: [push, pull_request]`,
      ``,
      `steps:`,
      `  install:`,
      `    image: mcr.microsoft.com/playwright:v1.48.0-noble`,
      `    commands:`,
      ...install,
    );
    for (const s of browser)
      if (s.absent) out.push(`  # ${ident(s.name)}: ${s.absent}`);
      else
        out.push(
          `  ${ident(s.name)}:`,
          `    image: mcr.microsoft.com/playwright:v1.48.0-noble`,
          `    commands:`,
          `      - ${y(s.command)}`,
        );
    out.push(``);
  }
  return out.join("\n");
}
